### ISSUE TITLE
about Houston dataset

### ISSUE THREAD

**Issue by bowenroom** [lms-07/AMS-M2ESL#1]
The link for the Houston dataset is invalid. The file has been permently moved. Please upload the dataset for Houston. Appreciate for the help!

**Comment by lms-07** [comment]
OK, I understand your request!

But I have tested the link, and I still could download the data set following the corresponding instructions on its page. 

Besides, this data set is under a customized copyright from the 2013 IEEE GRSS Data Fusion Contest and the Hyperspectral Image Analysis group at the University of Houston. It is clearly stated that **users may not distribute the dataset to others**. 

Therefore you may request the data personally.
